import { z } from 'zod';

export const createAlunoSchema = z.object({
    nome: z.string().min(2, 'O nome é obrigatório.'),
    data_nasc: z.string(),
    cpf: z.string().min(11, 'O CPF deve conter 11 caracteres.').max(11, 'O CPF deve conter 11 caracteres.'),
    andarilha: z.number().int().min(0).max(1),
    autorizacao_img: z.string().nullable().default(null),
    sexo: z.enum(['Masculino', 'Feminino']),
    receita_antitermico: z.string().nullable().default(null),
    cirurgia_qual: z.string().nullable().default(null),
    cirurgia_tempo: z.string().nullable().default(null),
    observacoes: z.string().nullable().default(null),
    
    foto: z.string().nullable().default(null),
    problema_saude: z.number().int().min(0).max(1).default(0),
    problema_saude_qual: z.string().nullable().default(null),
    alergia: z.number().int().min(0).max(1).default(0),
    alergia_qual: z.string().nullable().default(null),
    medicacao_continua: z.number().int().min(0).max(1).default(0),
    medicacao_qual: z.string().nullable().default(null),
    medicacao_tempo: z.string().nullable().default(null),
    fratura: z.number().int().min(0).max(1).default(0),
    fratura_qual: z.string().nullable().default(null),
    fratura_tempo: z.string().nullable().default(null),
    mamadeira: z.number().int().min(0).max(1).default(0),
    formula_qual: z.string().nullable().default(null),
    formula_quantidade_ml: z.string().nullable().default(null),
    chupeta: z.number().int().min(0).max(1).default(0),
    fralda: z.number().int().min(0).max(1).default(0),
    restricao_alimentar: z.number().int().min(0).max(1).default(0),
    restricao_descricao: z.string().nullable().default(null),
    cep: z.string().nullable().default(null),
    endereco: z.string().nullable().default(null),
    bairro: z.string().nullable().default(null),
    complemento: z.string().nullable().default(null),

    turma_id: z.number().int().positive(),
    funcionario_id: z.number().int().positive(),
});

export const updateAlunoSchema = z.object({
    nome: z.string().min(2).optional(),
    data_nasc: z.string().optional(),
    cpf: z.string().min(11).max(11).optional(),
    andarilha: z.number().int().min(0).max(1).optional(),
    autorizacao_img: z.string().nullable().optional(),
    sexo: z.enum(['Masculino', 'Feminino']).optional(),
    receita_antitermico: z.string().nullable().optional(),
    cirurgia_qual: z.string().nullable().optional(),
    cirurgia_tempo: z.string().nullable().optional(),
    observacoes: z.string().nullable().optional(),
    foto: z.string().nullable().optional(),
    problema_saude: z.number().int().min(0).max(1).optional(),
    problema_saude_qual: z.string().nullable().optional(),
    alergia: z.number().int().min(0).max(1).optional(),
    alergia_qual: z.string().nullable().optional(),
    medicacao_continua: z.number().int().min(0).max(1).optional(),
    medicacao_qual: z.string().nullable().optional(),
    medicacao_tempo: z.string().nullable().optional(),
    fratura: z.number().int().min(0).max(1).optional(),
    fratura_qual: z.string().nullable().optional(),
    fratura_tempo: z.string().nullable().optional(),
    mamadeira: z.number().int().min(0).max(1).optional(),
    formula_qual: z.string().nullable().optional(),
    formula_quantidade_ml: z.string().nullable().optional(),
    chupeta: z.number().int().min(0).max(1).optional(),
    fralda: z.number().int().min(0).max(1).optional(),
    restricao_alimentar: z.number().int().min(0).max(1).optional(),
    restricao_descricao: z.string().nullable().optional(),
    cep: z.string().nullable().optional(),
    endereco: z.string().nullable().optional(),
    bairro: z.string().nullable().optional(),
    complemento: z.string().nullable().optional(),

    turma_id: z.number().int().positive().optional(),
    funcionario_id: z.number().int().positive().optional(),
});